# Generated by Django 5.0.3 on 2024-03-24 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_movie_poster_alter_movie_runtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='poster',
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_img',
            field=models.ImageField(blank=True, upload_to='posters'),
        ),
    ]
